name: Sync OpenAPI definition to ReadMe

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

       # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.1.1
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.1.1
        with:
          rdme: openapi Work.json --key=rdme_xn8s9hed89640a8daa78461a7306245669d2e256550f1951978092e649be0e38ac7f94 --version=v3.0 --create

 
         # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.1.1
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.1.1
        with:
          rdme: openapi cvixapi.json --key=rdme_xn8s9hed89640a8daa78461a7306245669d2e256550f1951978092e649be0e38ac7f94 --version=v3.0 --create
