name: v1 version file

# Run workflow for every push to the `main` branch
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

   # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.1.1
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.1.1
        with:
          rdme: openapi ./v1/validapi/Attendance.json --key=rdme_xn8s9h7ec3d38e8936df2c360b841225481302a8edd1694adae4900a426916f912b1a1 --id=637a4b39cff60500423bd0c5 

  # Run GitHub Action to sync OpenAPI file at [path-to-file.json]
      - name: GitHub Action
        # We recommend specifying a fixed version, i.e. @8.0.2
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@8.0.2
        with:
         rdme: docs ./v1/docs/Authentication --key=rdme_xn8s9h7ec3d38e8936df2c360b841225481302a8edd1694adae4900a426916f912b1a1 --version=1.0
